- name: "Default Operating System configuration"
  ansible.builtin.set_fact:
    falcon_target_os: "{{ ansible_distribution }}"
    falcon_os_family: "{{ ansible_system | lower }}"
    falcon_os_version: "{{ ansible_distribution_major_version }}"
    falcon_sensor_update_policy_platform: "{{ ansible_system }}"

- name: "When OS is RedHat"
  ansible.builtin.set_fact:
    falcon_target_os: RHEL/CentOS/Oracle
  when: ansible_os_family == "RedHat"
